---
title: 'Reproducible Research: Peer Assessment 1'
output:
  html_document:
    keep_md: yes
  pdf_document: default
  word_document: default
---


## Loading and preprocessing the data
```{r simulate_data}
dataset_filename = "/activity.csv"
dataset_path = paste(getwd(),dataset_filename,sep="")

# loading data from file
dt = read.csv(dataset_path)

``` 

## What is mean total number of steps taken per day?

```{r steps_day}

# summing up the total steps taken per day
tab = aggregate(dt[!is.na(dt$steps), 1], list(dt[!is.na(dt$steps),2]), sum)

barplot(tab[,2], main="steps taken per day",
   xlab="Days", ylab = "Total steps")

# mean of the total number of steps taken per day
mean(tab[,2])

# median of the total number of steps taken per day
median(tab[,2])

```

## What is the average daily activity pattern?
```{r daily_activity}

tab = aggregate(dt[, 1], list(dt[ ,3]), mean, na.rm = T)

plot(tab[,1],tab[,2], type="l", xlab = "Intervals", ylab = "Average")

```

## Imputing missing values
```{r missing_values}
# Total number of missing values
sum(is.na(dt$steps))

j = 1
for(i in tab[,1]){
  dt$steps[is.na(dt$steps) & dt$interval == i] = tab[j,2]
  j = j + 1
}

# summing up the total steps taken per day
tab = aggregate(dt[,1], list(dt[,2]), sum)

barplot(tab[,2], main="steps taken per day",
   xlab="Days", ylab = "Total steps")

# mean of the total number of steps taken per day
mean(tab[,2])

# median of the total number of steps taken per day
median(tab[,2])

```
## Are there differences in activity patterns between weekdays and weekends?

```{r week}
library (lattice)

w = weekdays.POSIXt(as.POSIXct(dt$date))

# it must change to your language
weekend = w == 'sábado' | w == 'domingo'

w[weekend] = "weekend"
w[!weekend] = "weekday"

tab = aggregate(dt[, 1], list(w, dt[,3]), mean )

xyplot(x ~ Group.2 | Group.1, data = tab, type="l"  ,xlab = "Interval", ylab = "Number of steps", layout=c(1,2))

```
